### ISSUE TITLE
Feature Request: Option to open in "explainxkcd.com"

### ISSUE THREAD

**Issue by JimBarry** [paulrehkugler/xkcd#99]
The website ["explainxkcd.com/~"](https://www.explainxkcd.com/wiki/index.php/Main_Page) is a _[MediaWiki](https://www.mediawiki.org/wiki/MediaWiki)_-based wiki that includes an article for each of Randall's _**[xkcd](https://xkcd.com)**_ comics, where a discussion can ensue, and a crowdsourced meaning can be described and explained.

I think it might be a good idea if in your [XKCD app](https://apps.apple.com/us/app/xkcd/id303688284), if there was a button on the bottom _(along with the Share, Up, Random, and Down buttons)_, that opens that particular comic's associated "_explainxkcd.com_" page, in an in-app browser, or perhaps just kicked out to the device's system default browser app.

Thanks!!  Love your app!

**Comment by paulrehkugler** [comment]
Excellent idea. So excellent in fact, that it duplicates #35. Thanks for your input!

**Comment by JimBarry** [comment]
ouch, my bad.  ok thanks.
